/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiptSale_idRouteImport } from './routes/receipt.$sale_id'
import { Route as PayShopIdRouteImport } from './routes/pay/$shopId'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminSmartpayRouteImport } from './routes/admin/smartpay'
import { Route as AdminRevenueRouteImport } from './routes/admin/revenue'
import { Route as AdminReceiptSettingsRouteImport } from './routes/admin/receipt-settings'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminMerchantsRouteImport } from './routes/admin/merchants'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminBarcodesRouteImport } from './routes/admin/barcodes'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedSellRouteImport } from './routes/_authenticated/sell'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as ApiPublicWebhooksSmartpayRouteImport } from './routes/api/public/webhooks/smartpay'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptSale_idRoute = ReceiptSale_idRouteImport.update({
  id: '/receipt/$sale_id',
  path: '/receipt/$sale_id',
  getParentRoute: () => rootRouteImport,
} as any)
const PayShopIdRoute = PayShopIdRouteImport.update({
  id: '/pay/$shopId',
  path: '/pay/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSmartpayRoute = AdminSmartpayRouteImport.update({
  id: '/smartpay',
  path: '/smartpay',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReceiptSettingsRoute = AdminReceiptSettingsRouteImport.update({
  id: '/receipt-settings',
  path: '/receipt-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchantsRoute = AdminMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBarcodesRoute = AdminBarcodesRouteImport.update({
  id: '/barcodes',
  path: '/barcodes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSellRoute = AuthenticatedSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicWebhooksSmartpayRoute =
  ApiPublicWebhooksSmartpayRouteImport.update({
    id: '/api/public/webhooks/smartpay',
    path: '/api/public/webhooks/smartpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/products': typeof AuthenticatedProductsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sell': typeof AuthenticatedSellRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/barcodes': typeof AdminBarcodesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/receipt-settings': typeof AdminReceiptSettingsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/smartpay': typeof AdminSmartpayRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/pay/$shopId': typeof PayShopIdRoute
  '/receipt/$sale_id': typeof ReceiptSale_idRoute
  '/api/public/webhooks/smartpay': typeof ApiPublicWebhooksSmartpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/products': typeof AuthenticatedProductsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sell': typeof AuthenticatedSellRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/barcodes': typeof AdminBarcodesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/receipt-settings': typeof AdminReceiptSettingsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/smartpay': typeof AdminSmartpayRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/pay/$shopId': typeof PayShopIdRoute
  '/receipt/$sale_id': typeof ReceiptSale_idRoute
  '/api/public/webhooks/smartpay': typeof ApiPublicWebhooksSmartpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/sell': typeof AuthenticatedSellRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/barcodes': typeof AdminBarcodesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/receipt-settings': typeof AdminReceiptSettingsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/smartpay': typeof AdminSmartpayRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/pay/$shopId': typeof PayShopIdRoute
  '/receipt/$sale_id': typeof ReceiptSale_idRoute
  '/api/public/webhooks/smartpay': typeof ApiPublicWebhooksSmartpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/analytics'
    | '/dashboard'
    | '/history'
    | '/onboarding'
    | '/products'
    | '/profile'
    | '/sell'
    | '/subscription'
    | '/admin/analytics'
    | '/admin/barcodes'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/admin/merchants'
    | '/admin/notifications'
    | '/admin/receipt-settings'
    | '/admin/revenue'
    | '/admin/smartpay'
    | '/admin/support'
    | '/admin/system'
    | '/admin/transactions'
    | '/pay/$shopId'
    | '/receipt/$sale_id'
    | '/api/public/webhooks/smartpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/analytics'
    | '/dashboard'
    | '/history'
    | '/onboarding'
    | '/products'
    | '/profile'
    | '/sell'
    | '/subscription'
    | '/admin/analytics'
    | '/admin/barcodes'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/admin/merchants'
    | '/admin/notifications'
    | '/admin/receipt-settings'
    | '/admin/revenue'
    | '/admin/smartpay'
    | '/admin/support'
    | '/admin/system'
    | '/admin/transactions'
    | '/pay/$shopId'
    | '/receipt/$sale_id'
    | '/api/public/webhooks/smartpay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/login'
    | '/register'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/onboarding'
    | '/_authenticated/products'
    | '/_authenticated/profile'
    | '/_authenticated/sell'
    | '/_authenticated/subscription'
    | '/admin/analytics'
    | '/admin/barcodes'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/admin/merchants'
    | '/admin/notifications'
    | '/admin/receipt-settings'
    | '/admin/revenue'
    | '/admin/smartpay'
    | '/admin/support'
    | '/admin/system'
    | '/admin/transactions'
    | '/pay/$shopId'
    | '/receipt/$sale_id'
    | '/api/public/webhooks/smartpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  PayShopIdRoute: typeof PayShopIdRoute
  ReceiptSale_idRoute: typeof ReceiptSale_idRoute
  ApiPublicWebhooksSmartpayRoute: typeof ApiPublicWebhooksSmartpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$sale_id': {
      id: '/receipt/$sale_id'
      path: '/receipt/$sale_id'
      fullPath: '/receipt/$sale_id'
      preLoaderRoute: typeof ReceiptSale_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$shopId': {
      id: '/pay/$shopId'
      path: '/pay/$shopId'
      fullPath: '/pay/$shopId'
      preLoaderRoute: typeof PayShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/smartpay': {
      id: '/admin/smartpay'
      path: '/smartpay'
      fullPath: '/admin/smartpay'
      preLoaderRoute: typeof AdminSmartpayRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/receipt-settings': {
      id: '/admin/receipt-settings'
      path: '/receipt-settings'
      fullPath: '/admin/receipt-settings'
      preLoaderRoute: typeof AdminReceiptSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/barcodes': {
      id: '/admin/barcodes'
      path: '/barcodes'
      fullPath: '/admin/barcodes'
      preLoaderRoute: typeof AdminBarcodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sell': {
      id: '/_authenticated/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof AuthenticatedSellRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/webhooks/smartpay': {
      id: '/api/public/webhooks/smartpay'
      path: '/api/public/webhooks/smartpay'
      fullPath: '/api/public/webhooks/smartpay'
      preLoaderRoute: typeof ApiPublicWebhooksSmartpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSellRoute: typeof AuthenticatedSellRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSellRoute: AuthenticatedSellRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBarcodesRoute: typeof AdminBarcodesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMerchantsRoute: typeof AdminMerchantsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReceiptSettingsRoute: typeof AdminReceiptSettingsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSmartpayRoute: typeof AdminSmartpayRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBarcodesRoute: AdminBarcodesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMerchantsRoute: AdminMerchantsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReceiptSettingsRoute: AdminReceiptSettingsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSmartpayRoute: AdminSmartpayRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  PayShopIdRoute: PayShopIdRoute,
  ReceiptSale_idRoute: ReceiptSale_idRoute,
  ApiPublicWebhooksSmartpayRoute: ApiPublicWebhooksSmartpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
