ALTER TABLE public.shops
  ADD COLUMN IF NOT EXISTS plan TEXT NOT NULL DEFAULT 'basic',
  ADD COLUMN IF NOT EXISTS transaction_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS transaction_reset_date DATE NOT NULL DEFAULT CURRENT_DATE;